name: flickr
description: Serverside flickr interop library.
version: 0.0.1

environment:
  sdk: '>=1.0.0 <2.0.0'

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
  shelf_cors: '>=0.2.1 <0.3.0'
dependencies:
  http: '>=0.11.3+9 <0.12.0'
  shelf: '>=0.6.7+2 <0.7.0'
  shelf_route: '>=0.14.3 <0.15.0'
