name: flickr
description: Serverside flickr interop library.
version: 0.0.1

environment:
  sdk: '>=1.0.0 <2.0.0'

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
dependencies:
  http: '>=0.11.3+9 <0.12.0'
